version: '3'

services:
  django:
    build:
      dockerfile: ./docker/gwlab_cwfollowup_django.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlab_cwfollowup_django:0.6
    container_name: gwlab_cwfollowup_django
    environment:
      MYSQL_ROOT_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_DATABASE: gwlab_cwfollowup
      MYSQL_USER: django
      MYSQL_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_HOST: db
    ports:
      - "8000"
    depends_on:
      - db

  nginx:
    build:
      dockerfile: ./docker/gwlab_cwfollowup_nginx.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlab_cwfollowup_nginx:0.1
    container_name: gwlab_cwfollowup_nginx
    ports:
      - "8000:8000"
    depends_on:
      - static
      - django
      
  static:
    build:
      dockerfile: ./docker/gwlab_cwfollowup_static.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlab_cwfollowup_static:0.3
    container_name: gwlab_cwfollowup_static
    ports:
      - "8000"
      
  db:
    image: mysql:5.7
    container_name: gwlab_cwfollowup_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_DATABASE: gwlab_cwfollowup
      MYSQL_USER: django
      MYSQL_PASSWORD: 76vcqmGKP19Z1AEx
    volumes:
      - var_lib_mysql:/var/lib/mysql
  
volumes:
  var_lib_mysql:
