# Generated by Django 2.2.16 on 2021-09-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwfollowup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwfollowupjob',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cwjob',
            name='viterbi_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cwjobcandidate',
            name='asini',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cwjobcandidate',
            name='orbit_period',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cwjobcandidate',
            name='orbit_tp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cwjobcandidate',
            name='source_dataset',
            field=models.CharField(choices=[['o1', 'O1'], ['o2', 'O2'], ['o3', 'O3'], ['o4', 'O4']], default='o1', max_length=2),
        ),
    ]
