# Generated by Django 2.2.16 on 2021-09-15 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwfollowup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWFollowup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedCWJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedCWJobCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_dataset', models.CharField(blank=True, choices=[['o1', 'O1'], ['o2', 'O2'], ['o3', 'O3'], ['o4', 'O4']], default='o1', max_length=2, null=True)),
                ('candidate_frequency', models.FloatField()),
                ('target_binary', models.BooleanField(blank=True, default=True, null=True)),
                ('orbit_tp', models.FloatField(blank=True, null=True)),
                ('asini', models.FloatField(blank=True, null=True)),
                ('orbit_period', models.FloatField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='cwfollowup.UploadedCWJob')),
            ],
        ),
        migrations.CreateModel(
            name='ViterbiJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('viterbi_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataparameter',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dataparameter',
            name='job',
        ),
        migrations.RemoveField(
            model_name='search',
            name='job',
        ),
        migrations.RemoveField(
            model_name='searchparameter',
            name='job',
        ),
        migrations.RemoveField(
            model_name='searchparameter',
            name='search',
        ),
        migrations.AddField(
            model_name='cwfollowupjob',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cwfollowupjob',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterUniqueTogether(
            name='cwfollowupjob',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='DataParameter',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='SearchParameter',
        ),
        migrations.AddField(
            model_name='cwfollowup',
            name='followup_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='cwfollowup.CWFollowupJob'),
        ),
        migrations.RemoveField(
            model_name='cwfollowupjob',
            name='is_ligo_job',
        ),
        migrations.RemoveField(
            model_name='cwfollowupjob',
            name='job_controller_id',
        ),
        migrations.RemoveField(
            model_name='cwfollowupjob',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='cwfollowupjob',
            name='private',
        ),
        migrations.AddField(
            model_name='cwfollowupjob',
            name='uploaded_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='followup_job', to='cwfollowup.UploadedCWJob'),
        ),
        migrations.AddField(
            model_name='cwfollowupjob',
            name='viterbi_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='followup_job', to='cwfollowup.ViterbiJob'),
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AlterUniqueTogether(
            name='cwfollowup',
            unique_together={('followup_job', 'followup')},
        ),
    ]
