# Generated by Django 2.2.16 on 2021-09-16 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwfollowup', '0002_auto_20210915_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwfollowup',
            name='followup_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='cwfollowup.CWFollowupJob'),
        ),
        migrations.AlterField(
            model_name='uploadedcwjobcandidate',
            name='target_binary',
            field=models.BooleanField(default=True),
        ),
    ]
