# Generated by Django 2.2.16 on 2021-10-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwfollowup', '0002_auto_20210928_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwjobcandidate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='cwfollowup.CWJob'),
        ),
    ]
