# Generated by Django 2.2.16 on 2021-11-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwfollowup', '0003_auto_20211028_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwfollowup',
            name='followup_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='cwfollowup.CWFollowupJob'),
        ),
    ]
