# Generated by Django 2.2.16 on 2021-09-17 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwfollowup', '0003_auto_20210916_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwfollowupjob',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cwfollowup',
            name='followup_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='cwfollowup.CWFollowupJob'),
        ),
    ]
