# Generated by Django 2.2.16 on 2021-11-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwfollowup', '0004_auto_20211109_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwfollowupjob',
            name='job_controller_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
