# Generated by Django 2.2.28 on 2023-03-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwfollowup', '0007_auto_20230131_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwfollowupjob',
            name='candidate_group_id',
            field=models.CharField(default='', max_length=24),
        ),
    ]
